### ISSUE TITLE
Passing ... to prcomp

### ISSUE THREAD

**Issue by lgatto** [jkrijthe/Rtsne#14]
Currently `Rtsne` has `...` but doesn't use them to pass parameters to inner functions. Would you consider a patch to pass them to `prcomp`? 

The reason for this is to allow centering and scaling (default is `FALSE`) the data, which seems to make a difference in our case - see [this issue](https://github.com/lgatto/pRoloc/issues/96) (in particular from [this comment](https://github.com/lgatto/pRoloc/issues/96#issuecomment-287072402) on) for details.

An alternative to passing `...` to `prcomp` would be to have explicit `scale` (and possible `center`) parameters in `Rtsne`.

**Comment by jkrijthe** [comment]
Thanks for the suggestion. The reason the defaults are set this way is that
the command line interface on which the package is based uses these
defaults as well. I had assumed that if someone would like to use different
preprocessing, one would preprocess the data outside of the Rtsne function.

I would not be in favor of passing ... to prcomp, but explicit parameters
as you suggest could be a reasonable solution if you prefer this over the
explicit preprocessing outside the Rtsne function.

**Comment by lgatto** [comment]
Thank you for your feedback. Which suggestion for explicit parameters would you prefer:

* `prcomp.scale` and `prcomp.center`, with defaults `FALSE` and `TRUE` respectively, to match the `prcomp` defaults. This assumes that `tol` will never be set.

* A `prcomp.args` list to deal with all arguments and passed with `do.call(prcomp, prcomp.args)` to support all arguments.

I could also implement explicit pre-processing within my function to sort out my issue, if you prefer to leave the code as it is not. Let me know and I will send a PR accordingly.

**Comment by jkrijthe** [comment]
I had no specific need to add it, but if it simplifies your code I would be
glad to accept a PR. I think I would prefer your first option with
parameter names "pca_scale" and "pca_center" so that it matches the "pca"
and underscores used in the current parameter names.

**Comment by jkrijthe** [comment]
Thanks again for the request. I added these parameters in 8870024ae5aa30a3b46c8b82b550f56ea7bbd988.
Hope this helps!

**Comment by lgatto** [comment]
Fantastic, thank you.
