### ISSUE TITLE
CRAN submission and/or version bump

### ISSUE THREAD

**Issue by lgatto** [jkrijthe/Rtsne#15]
It would be useful to bump the package version (to `0.12.1`, for example), to make it easier for dependencies to make use of new features in `Rtsne`. With a new version number, my package could import `Rtsne (>= 0.12.1) and make sure the pca pre-processing arguments are available.

A push to CRAN would be helpful at some point, to make sure that the latest version of `Rtsne` is installed/updated automatically.

**Comment by jkrijthe** [comment]
I agree. I have bumped the version to 0.13. I would like to wait with a CRAN submission until the end of the week to see if any issues come up that are caused by the recent changes.

**Comment by lgatto** [comment]
Thank you for the version bump. End of the week is fine, cheers.

**Comment by lgatto** [comment]
Hi @jkrijthe - I was wondering if you had a chance to look into the CRAN submission.

**Comment by jkrijthe** [comment]
Thanks for the reminder. I will try to do this later today.

**Comment by jkrijthe** [comment]
It's on CRAN now.
