### ISSUE TITLE
RTsne output sometimes gives fewer rows than the input data frame

### ISSUE THREAD

**Issue by dracovich** [jkrijthe/Rtsne#17]
I'm unsure if this is intended? And if it is, is there a way to see what rows are not calculated? I want to be able to cbind the results to my original data (so that i can plot it using color labels from the original data),  but a mismatch between input and output dimensions obviously makes this impossible.

I'm running RTsne on a 15000x3000 data frame with no duplicates, it gives no errors or warnings and completes without issues, but the Y table in the output has ~500 less rows than the input.

**Comment by jkrijthe** [comment]
Thanks for opening an issue for this. Do you happen to have a reproducible example?

**Comment by dracovich** [comment]
Ok well i feel like an idiot, i thought i'd checked all possible problems, and made sure there was no NA's and duplicates, but as i was getting ready to export the data so you could verify, i saw there were NA columns on a few a few of the rows, which seems to have been the issue.

Apologies for the frivilous issue report, but perhaps some kind of warning message if NA's are encountered would be in order?

**Comment by jkrijthe** [comment]
Thank you for pointing this out. I agree this is behaviour where rows with NAs are silently dropped from data.frame inputs is not the expected behaviour and should generate an error instead. Same for matrix inputs with NAs which I guess currently cause R to crash...

I will keep this issue open until I have time to fix this.

**Comment by jkrijthe** [comment]
This behaviour should be fixed by b7a39d4e0224e269c9ad4a3858db8b63f70235fc. Thanks again!
