### ISSUE TITLE
Clearer Parameter Documentation

### ISSUE THREAD

**Issue by DarioS** [jkrijthe/Rtsne#22]
For example, for `X` it would be worthwhile to specify that the rows are for samples and the columns are for variables. The opposite is usually true in bioinformatics. Also, `perplexity` is vauguely described as "numeric; Perplexity parameter". It would be good to explicitly state the range of values which it can take to avoid the "Perplexity is too large." error (i.e. one less than the number of samples divided by 3).

**Comment by jkrijthe** [comment]
Thank you for the suggestion! I agree this should be clearer and will include your two suggestions when I have time.

**Comment by jkrijthe** [comment]
Thanks again, I added clarification to the parameter descriptions you mentioned in 07a67b6ad3a3e5201f375d850fc37e4a286504c4. If you have any other suggestions please let me know.
