### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by RoyalTS** [jkrijthe/Rtsne#24]
How does Rtsne compare to other tsne implementations for R?

**Comment by jkrijthe** [comment]
I am not sure exactly which implementations your are referring to, but at the time I initially developed the package, the main alternative was the tsne package. A small benchmark on 2000 MNIST digits shows the following:

```
library(Rtsne)
library(tsne)
library(createdatasets)
df_mnist <- createMNIST()

df_sampled <- df_mnist[sample(1:nrow(mat_mnist),1000),]
mat_mnist <- as.matrix(df_sampled[,!(colnames(df_sampled) == "Class")])

system.time(res_rtsne <- Rtsne(mat_mnist))
system.time(res_rtsne_exact <- Rtsne(mat_mnist, theta=0.0))
system.time(res_tsne <- tsne(mat_mnist))

plot(res_tsne, col=df_sampled$Class)
plot(res_rtsne$Y, col=df_sampled$Class)
plot(res_rtsne_exact$Y, col=df_sampled$Class)
```
With timings:
```
Rtsne
   user  system elapsed 
 11.861   0.058  11.953
Rtsne (exact)
   user  system elapsed 
 13.637   0.058  13.736
tsne 
   user  system elapsed 
152.029  25.747 179.367
```
And outputs:

![rplot](https://user-images.githubusercontent.com/651961/27728784-8670e978-5d83-11e7-8e09-dbc50347ebda.png)
![rplot01](https://user-images.githubusercontent.com/651961/27728785-86899c02-5d83-11e7-86a6-0ff065c8d304.png)
![rplot02](https://user-images.githubusercontent.com/651961/27728786-868c9934-5d83-11e7-8397-1c4f7db8c651.png)

So the C++ implementation in Rtsne is about 10 times faster than the R implementation in tsne, (although note that the default parameters used are slightly different in both cases, which I do not expect to change the results much). The Barnes-Hut implementation in Rtsne will show an even larger difference when the dataset size grows, with more representative comparisons in Laurens van der Maaten's paper. 

Having said that, tsne has some features, like allowing for callbacks during the running of the algorithm that Rtsne does not have (see #20).

There are definitely ways to speed up the current implementation. See for instance the discussion in #16. 

Hope this helps!

**Comment by RoyalTS** [comment]
Thanks! That was extremely helpful in deciding whether to use the package or not. Worth putting somewhere more accessible somewhere perhaps.

**Comment by jkrijthe** [comment]
Good point, perhaps I'll add something like this to the readme. I've you are interested in better performance, I am working on some performance improvements in a separate branch (openmp), discussed in #16.

**Comment by RoyalTS** [comment]
Just switching over from `tsne` did the trick for me. But good to know there's more improvements in the pipeline!
