### ISSUE TITLE
add CXX flags for openmp

### ISSUE THREAD

**Issue by pkharchenko** [jkrijthe/Rtsne#25]
openmp branch was not compiling with openmp enabled. While PKG_CFLAGS have been specified in Makevars, the code checks #ifdef _OPENMP, which requires openmp to be enabled during compilation as well. This can be fixed by adding the following line to Makevars:
PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
Thanks!

**Comment by jkrijthe** [comment]
Thanks! I had not realized I only enabled this in my local Makevars configuration. Should be fixed now.
