### ISSUE TITLE
Performance Improvements via PCA

### ISSUE THREAD

**Issue by daniel-wells** [jkrijthe/Rtsne#26]
I see there is an effort to increase performance via parallel tSNE in #16. However, for some datasets the PCA (via SVD) preprocessing step dominates the runtime.

For example take a RNA expression dataset of single cells. There are 5069 cells, and 23556 genes (which I subset down to 5k)
```
# Download data (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE75330)
marques <- data.table::fread("curl ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE75nnn/GSE75330/suppl/GSE75330%5FMarques%5Fet%5Fal%5Fmol%5Fcounts2%2Etab%2Egz | zcat")
mat_marques <- t(as.matrix(marques[,-"cellid", with=FALSE]))

# subset to 5k genes and do PCA via SVD
system.time(marques_pca_A <- prcomp(mat_marques[,1:5000]))

# run Rtsne
system.time(marques_rtsne_A <- Rtsne::Rtsne(marques_pca_A$x[,1:50], pca=FALSE))
```

```
   user  system elapsed
503.787   5.419 511.918

   user  system elapsed
 39.383   0.816  40.448
```

The PCA step takes 12x longer than the tSNE step. It may not be obvious to some users that it's the PCA step which is taking most of the time, or that there are faster alternatives. I think it would be good to have a note in the manpage recommending doing the PCA step seperately with a faster package for large datasets e.g. flashpcaR

```
system.time(marques_pca_B <- flashpcaR::flashpca(mat_marques[,1:5000], ndim=50, stan="center"))
```
```
   user  system elapsed 
  3.400   0.273   3.682
```

Or perhaps a warning message when attempting to run Rtsne on a matix when both dimensions are largeish e.g.
```
if(min(dim(X)) > 2500){
warning("Using pca=TRUE can be slow for large datasets. Consider computing PCA seperately with a different package (e.g. flashpcaR).")
}
```
(the time complexity of SVD is O(min(pn^2, np^2)) )

**Comment by jkrijthe** [comment]
Thank you for the suggestion! I agree it makes a lot of sense to mention this in the documentation, or even use the faster method when the user has the additional package installed. I have little experience with these implementations, however. Is there a reason to suggest flashpcaR over the irlba, for instance?

**Comment by daniel-wells** [comment]
Yeah automatic detection would be great! I find flashpcaR to be about twice as fast vs irlba but doesn't seem to be avaliable on CRAN and I think irlba has a larger install base especially outside genetics so maybe that would be the main one to check for.
```
> mat_marques <- scale(mat_marques[,1:5000],T,F)
> system.time(marques_pca_B <- flashpcaR::flashpca(mat_marques, ndim=50, stand="none", divisor="none"))
   user  system elapsed 
  3.120   0.192   3.314 
> system.time(marques_pca_C <- irlba::prcomp_irlba(mat_marques, 50, center=FALSE))
   user  system elapsed 
  7.558   0.090   7.659 
```
(centered seperately due to some integer/centering related bug in irlba not yet fixed in CRAN)

**Comment by jkrijthe** [comment]
An alternative might be the RSpectra package which I suppose uses some of the same functions that are used in flashpcaR.

**Comment by daniel-wells** [comment]
Yes, although I'm not sure to what degree the code is copied over. In my hands RSpectra seems to be slower than both flashpcaR and irlba.
```
> system.time(marques_pca_D <- RSpectra::svds(mat_marques, 50))
   user  system elapsed 
  9.643   0.026   9.686 
```

**Comment by yixuan** [comment]
@daniel-wells I haven't taken time to examine the problem carefully, but I guess part of the difference is due to the centralization of the matrix. PCA basically does `svds()` on the matrix subtracted by the column means, not the original matrix.

**Comment by daniel-wells** [comment]
@yixuan Here I centered the matrix in a separate step before passing the matrix to the functions so the `mat_marques` passed to `svds()` is centered:
`mat_marques <- scale(mat_marques[,1:5000],T,F)`
Sorry maybe it's a bit confusing the code is split into multiple comments rather than completely self contained. Or maybe I'm misunderstanding?

**Comment by jkrijthe** [comment]
For completeness: in my small experiments on 1000x5000 matrices, RSpectra was slightly faster than irlba.

I'm a bit unsure what I should add to the package. I'm currently considering adding the the truncated pca as a non-default optional setting and using irlba to do it, because I don't like changing the default behaviour that current users might depend on for reproducibility. Another option is to simply refer to irlba and RSpectra in the documentation.

**Comment by yixuan** [comment]
@daniel-wells My bad, I didn't notice that line. 😥
I was curious since `flashpcaR` and `RSpectra` both depend on Spectra. Something mysterious here...

**Comment by daniel-wells** [comment]
I also find RSpectra slightly faster than irlba for 1000x5000:

```
mat_marques <- scale(mat_marques[,1:1000],T,F)
> system.time(marques_pca_B <- flashpcaR::flashpca(mat_marques, ndim=50, stand="none", divisor="none"))
   user  system elapsed 
  0.646   0.034   0.705 
> system.time(marques_pca_C <- irlba::prcomp_irlba(mat_marques, 50, center=FALSE))
   user  system elapsed 
  2.221   0.048   2.310 
> system.time(marques_pca_D <- RSpectra::svds(mat_marques, 50))
   user  system elapsed 
  1.819   0.004   1.827 
```

I agree it's probably a good idea to keep defaults for reproducibility. I think either of those options would be good. I do think it would be a good idea to add a warning or message when min(dim)~>2500, currently even when `verbose=TRUE` nothing is output until after the pca has completed: "Read the data matrix successfully" so it might not even be obvious that PCA is the slow step.
