### ISSUE TITLE
The effect with the order of features

### ISSUE THREAD

**Issue by sky-peng** [jkrijthe/Rtsne#27]
Hi
I have some questions about Rtsne. For the database of iris, the default order is "Sepal.Length Sepal.Width Petal.Length Petal.Width", but i have a different result of Rtsne when i change the order as "Petal.Length Petal.Width Sepal.Length Sepal.Width" (or other orders). I'm very confused that the result is effected and changes by the features order.
What's more, I have try the different pipeline and get the different results, the only difference of the two pipeline is:
tsne1 <- Rtsne(iris_matrix)
tsne2 <- Rtsne(dist(iris_matrix))

**Comment by jkrijthe** [comment]
I agree you would want to get the same results in both cases (as long as you use the same seed using set.seed). The reason I have not been able to make this happen (I think) is that tiny changes in the distance calculations (compare, for instance, the dist() objects for the two feature orderings, they are not exactly the same) will affect the tsne optimisation and this lead to a different solution. If you have a different explanation of the effect, please let me know. Hope this helps!

**Comment by sky-peng** [comment]
Thanks for you answer!
I try again with your suggestions (i.e. use the same seed using set.seed), but unfortunately, the results are still different, and the good news is that the difference is not big.
And i agree your explanation may be the reasonable reason about the dist() question.

**Comment by jkrijthe** [comment]
Just to be clear: the same explanation holds for the matrix input. In that case for distances are calculated in the C++ code, but the same reasoning holds.
