### ISSUE TITLE
Variance needed for both axes

### ISSUE THREAD

**Issue by PhrenoVermouth** [jkrijthe/Rtsne#30]
Hi!
We know in PCA results there's a  'percentVar' for explaining contributions of each of components. 
Is there a similar one for tSNE dimensionality reduction?
Thanks!

```
> str(tsne_out)
List of 13
 $ theta              : num 0.5
 $ perplexity         : num 30
 $ N                  : int 149
 $ origD              : int 4
 $ Y                  : num [1:149, 1:2] -17.7 -20.1 -20 -20.4 -17.7 ...
 $ costs              : num [1:149] 1.03e-04 -2.29e-04 -5.16e-05 -3.76e-04 -3.55e-05 ...
 $ itercosts          : num [1:20] 44.6 45.2 43 45.4 44.3 ...
 $ stop_lying_iter    : int 250
 $ mom_switch_iter    : int 250
 $ momentum           : num 0.5
 $ final_momentum     : num 0.8
 $ eta                : num 200
 $ exaggeration_factor: num 12
```

**Comment by jkrijthe** [comment]
The `costs` variable contains some measure of how well each object is represented, but in general, I do not think there is a straightforward measure of how much each dimension "adds" to the representation of the objects. Note that t-sne does not try to explain the total variance of the data (of which you could explain a certain percentage, like the principal components), but rather the local configuration of objects. See the help files and the original t-sne papers for more details.
