### ISSUE TITLE
Rtsne error: "Remove duplicates before running TSNE."

### ISSUE THREAD

**Issue by DadongZ** [jkrijthe/Rtsne#41]
I have a matrix with dimension 19481x9187 and I got error message ""Remove duplicates before running TSNE." When I run below code:
```
dim(est)
[1] 19481 9187
is.matrix(est)
[1] TRUE
est.rtsne<-Rtsne(X=est, check_duplicates=FALSE, dims=2, initial_dims=10)
```
Do you have some suggestions?

**Comment by jkrijthe** [comment]
What version are you using (on CRAN or from Github)? And can you create a reproducible example?

**Comment by DadongZ** [comment]
It's v0.13 from CRAN. I thought it's probably due to high dimension because I am able to run it using a subset such like est[1:2000, 1:500] but encountered error when run it in full matrix.

**Comment by jkrijthe** [comment]
But the subset might not contain the duplicates.

What surprises me is that you would get the error when using option check_duplicates=FALSE, since in that case no duplicates check should be performed.
