### ISSUE TITLE
Single-threaded on Windows, multi-threaded on Linux

### ISSUE THREAD

**Issue by ekinda** [jkrijthe/Rtsne#48]
Hi. The Rtnse function is running only on a single thread on Windows, while it is parallelized on Linux. Both operating systems are running on the same computer.

However, the same happens with running only PCA as well, which t-SNE performs in the beginning. So this is probably not an issue of this package, but I couldn't find a solution anywhere and wanted to try my chances here. Thanks in advance.

**Comment by ekinda** [comment]
Note: I tried using num_threads = 0.

**Comment by SamGG** [comment]
Hi. I am quite surprised. Could you send the sessionInfo after having run a Rtsne call?

**Comment by jkrijthe** [comment]
It sounds like it is not an Rtsne specific issue, if it also happens for other packages using OpenMP. Are there more details that you can share?
