### ISSUE TITLE
Add option for density-preserving t-SNE

### ISSUE THREAD

**Issue by Alanocallaghan** [jkrijthe/Rtsne#49]
Would you be interested in a PR to include an option to use the density-preserving modification to t-SNE introduced by [Narayan et al. (2020)](https://www.biorxiv.org/content/10.1101/2020.05.12.077776v1.full.pdf)?

**Comment by Alanocallaghan** [comment]
Implemented in densvis

**Comment by jkrijthe** [comment]
Apologies for the (very) late reply... Great that you made this available!
