### ISSUE TITLE
Error in library Rtsne

### ISSUE THREAD

**Issue by hahia** [jkrijthe/Rtsne#50]
Hello, when I library(Rtsne), there has an error
![image](https://user-images.githubusercontent.com/49113803/105651451-e8c0a280-5ef1-11eb-8a45-9645b46e94dd.png)

sessioninfo()
![image](https://user-images.githubusercontent.com/49113803/105651482-fbd37280-5ef1-11eb-8afe-8c4f4feb1d39.png)

**Comment by jkrijthe** [comment]
Seems like a mismatch between the available libgomp and the one used when compiling? How did you install the package?

**Comment by hahia** [comment]
> Seems like a mismatch between the available libgomp and the one used when compiling? How did you install the package?
I use 
install.packages("Rtsne") # Install Rtsne package from CRAN

In Linux, I can library Rtsne
![image](https://user-images.githubusercontent.com/49113803/105691272-fd278e00-5f37-11eb-90ae-4ed4e1889fc4.png)

but in the Rstudio, I can't library Rtsne
![image](https://user-images.githubusercontent.com/49113803/105691429-2e07c300-5f38-11eb-9292-257d163df9bb.png)

Thank you for your help.

**Comment by SamGG** [comment]
Hi,
In the Rstudio console, the reported version of R is 3.6.2 whereas it seems to be 4.0.3 in the last capture. It sounds to me as if Rstudio is not aware of R4.0.3 or glued with R.3.6.2. Check the version of R in Tools/Project options/R general.
HTH

**Comment by hahia** [comment]
> Hi,
> In the Rstudio console, the reported version of R is 3.6.2 whereas it seems to be 4.0.3 in the last capture. It sounds to me as if Rstudio is not aware of R4.0.3 or glued with R.3.6.2. Check the version of R in Tools/Project options/R general.
> HTH
