### ISSUE TITLE
tsne versus som

### ISSUE THREAD

**Issue by llevoc** [jkrijthe/Rtsne#51]
I have successfully generated a SOM for a dataset of ~20k variables (drugs) for observations (GI50) against 422 protein targets. Using the som_init tools (ratio of first 2 principal components) for setting SOM dimensions yields a SOM of ~1000 clusters (xdim=20 ydim=50).
The 422 protein targets are labelled according to the protein target with a suffix associated with 7 protein classes. Each SOM cluster's members can be parsed for which of the 7 protein classes are most represented within each SOM cluster. 

My problem (question) is how to generate a tsne result where each element is colored according to the 7 protein classes. Any suggestions would be appreciated. 

In order to complete this analysis, enabling parallelization would be very helpful. Is there a 'parallel' option on the tsne command.

Respectfully,
llevoc

**Comment by jkrijthe** [comment]
This sounds like a question about plotting, and not an issue with the Rtsne package. I would also suggest providing a reproducible example to show where or how you current approach fails. Regarding parallelisation: please have a look at the num_threads parameter of the Rtsne function.

Good luck!
