### ISSUE TITLE
Rtsne on large dataset 

### ISSUE THREAD

**Issue by Ivy-ops** [jkrijthe/Rtsne#52]
Hi developer, 
I have a dataset of 40 million observations and 40 variables. May I know how to reduce the dimension of this type of large dataset, get the coordinates of 40 million observations to visualize in 2-dimension? 
Thanks, 
-Ivy

**Comment by jkrijthe** [comment]
I do not have experience with such large datasets, but if it takes too long (even when using multiple cores) or uses too much memory, and you do not want to subsample, I guess you would need a different approximation than Barnes-Hut to make this work (for instance, by using interpolation points, as in https://www.nature.com/articles/s41592-018-0308-4). But that it beyond scope of this package.

Hope this helps.

**Comment by SamGG** [comment]
FitSNE is fast but I am not sure whether it addresses large datasets. [Opt-SNE](https://www.nature.com/articles/s41467-019-13055-y) has been tested with more than 10 millions observations. I will second Jesse concerning subsampling: in my experience, as a visualization tool, I never needed more than 300~500 k observations. Of course, you probably know about UMAP as implemented in [uwot](https://github.com/jlmelville/uwot).
Best.
