### ISSUE TITLE
Memory not released with multi-threading

### ISSUE THREAD

**Issue by ivokwee** [jkrijthe/Rtsne#56]
Hi.
 
I noticed that when running Rtsne with num_thread=0 the used memory can increase dramatically and doesn't get released after Rtsne is finished, even after doing a call to gc(). This is especially noticable on a high-core machine, with 64 threads. When run with num_threads=1 memory is 181MB before running Rtsne and is 205MB after the call. With num_threads is 0 (on a 64 threads machine) the used mem after Rtsne is 6604MB.  Even after calling gc() I cannot release the memory. In fact, setting num_threads artificially high to 2014, the used memory is 20GB. 

Not 100% sure if my way to calculate memory usage using /proc is correct. 

Any thoughts?

```
mem.used <- function(digits = 0) {
    file <- paste("/proc", Sys.getpid(), "stat", sep = "/")
    what <- vector("character", 52)
    vsz <- as.numeric(scan(file, what = what, quiet = TRUE)[23])
    vsz <- vsz / (1024**2) ## MB
    mem <- paste0(round(vsz, digits), "MB")
  mem
}

X <- matrix(rnorm(1000*100),1000,100)

mem.used()
system.time( pos <- Rtsne::Rtsne(t(X), num_threads = 1) )
mem.used()

system.time( pos <- Rtsne::Rtsne(t(X), num_threads = 128) )
mem.used()

gc()
mem.used()
```

**Comment by SamGG** [comment]
I am not the developer.

a) computing memory use is very tricky in R. Did you look at [Advanced R by Hadley Wickham](http://adv-r.had.co.nz/memory.html)?

b) t(X) means that the goal is to map 100 points from a 1000-dimensions space, which ends up in 100 points in a 50-dimensions space because of the PCA. Just to be sure you are OK with that.

c) here is the result of a simulation on my small laptop (4 cores, Windows 10 x64)

Hope this helps,
Samuel

``` r
library(pryr)
mem_used()
#> 47.8 MB
X <- matrix(rnorm(10000*100),10000,100)

mem_used()
#> 56.1 MB
system.time( pos <- Rtsne::Rtsne(X, num_threads = 1) )
#>    user  system elapsed 
#>   50.54    0.14   50.24
mem_used()
#> 56.8 MB

system.time( pos <- Rtsne::Rtsne(X, num_threads = 4) )
#>    user  system elapsed 
#>   52.97    0.09   31.08
mem_used()
#> 56.8 MB

gc()
#>           used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells  696567 37.3    1535408   82  1110242 59.3
#> Vcells 2227013 17.0    8388608   64  8388558 64.0
mem_used()
#> 56.8 MB

sessionInfo()
#> R version 4.3.1 (2023-06-16 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8   
#> [3] LC_MONETARY=French_France.utf8 LC_NUMERIC=C                  
#> [5] LC_TIME=French_France.utf8    
#> 
#> time zone: Europe/Warsaw
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.10.1     digest_0.6.32     fastmap_1.1.1     xfun_0.39        
#>  [5] magrittr_2.0.3    glue_1.6.2        R.utils_2.12.2    knitr_1.43       
#>  [9] htmltools_0.5.5   rmarkdown_2.22    lifecycle_1.0.3   cli_3.6.1        
#> [13] R.methodsS3_1.8.2 vctrs_0.6.3       reprex_2.0.2      withr_2.5.0      
#> [17] compiler_4.3.1    R.oo_1.25.0       R.cache_0.16.0    purrr_1.0.1      
#> [21] rstudioapi_0.14   tools_4.3.1       evaluate_0.21     yaml_2.3.7       
#> [25] rlang_1.1.1       fs_1.6.2
```

<sup>Created on 2024-01-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ivokwee** [comment]
thanks for the reply and pointers! I also found out that actually querying /proc/[PID]/stat is not reliable for multithreading (lost the reference...). Seems /proc/[PID]/status gives RSS memory and shows better the real memory usage: virtual size vs resident size. I guess I could have used pryr::mem_used as you did. OK false alarm then. closing this issue. thanks.
